### ISSUE TITLE
Timeline for SalesforceIQ API address change?

### ISSUE THREAD

**Issue by zapnap** [relateiq/ruby-sdk#11]
Noticed that the API documentation has been updated to reference `api.salesforceiq.com` but the gem is still pointing to `api.relateiq.com`. I assume this will continue to work for the foreseeable future? Are we in any immediate risk of this breaking? Didn't see any sort of timeline for migration... Thanks!

**Comment by Xavdidtheshadow** [comment]
Definitely no risk of breaking. It'll redirect for a while. The next time we cut a release for the gem, it'll include the updated url and your apps won't notice a service disruption. 

I'll close this issue when that change is in.
