### ISSUE TITLE
No way to get account fields through gem

### ISSUE THREAD

**Issue by zapnap** [relateiq/ruby-sdk#7]
As far as I can tell this endpoint isn't wrapped by the gem?

https://api.relateiq.com/#/curl#documentation_accounts_account-fields_get-all-fields

**Comment by Xavdidtheshadow** [comment]
@zapnap you're right! i'll get that done tomorrow. i'll also merge in your fixes tonight or tomorrow, thanks for the contributions!

**Comment by zapnap** [comment]
:thumbsup:

**Comment by Xavdidtheshadow** [comment]
@zapnap deployed a new version: `1.2.0`

**Comment by zapnap** [comment]
Great thanks!
